### PR TITLE
Shibboleth integration for IdP 3.x

### PR DESCRIPTION
**Pull request by vladimir-mencl-eresearch**
Add Shibboleth Integration for IdP 3.x (3.2+) based on existing Shibboleth Integration code for IdP 2.x.

Add this in a new hiearchy under `shibboleth-integration-idpv3` (parallel with existing `shibboleth-integration` hierarchy).

Replace VhrFilter with VhrRemoteUserAuthServlet based on IdP 3.x RemoteUserAuthServlet (and code from VhrFilter).

Include sample configuration in `configuration/idpv3/addto-web.xml`

### CODE REVIEW

**Comment by vladimir-mencl-eresearch** [comment]
I had to fix ECP yesterday which wasn't working - turns out the approach with HttpRequestWrapper no longer works with IdPv3.  Passing the username in request attributes does he trick instead.  So I've now also removed the VhrFilter and VhrRequestWrapper classes fro m the IdPv3 branch - it should be complete now.

**Comment by bradleybeddoes** [comment]
This all looks good but I am slightly concerned that merging it would make it seem like the AAF has run VH against IdP v3, which we likely never will.

I was thinking a nice middle ground might be adding a `README.md` here that:

* Properly attributes this work to Tuakiri
* Indicates that this is code which Tuakiri has running in production but has not yet been exercised by the AAF.

A paragraph would be all that is needed imho.

Thoughts?

**Comment by vladimir-mencl-eresearch** [comment]
Happy to add that - will do this shortly.

The code anyway used some extensions that I've done in the Tuakiri fork.  The ShibInt code would still work with the AAF web-app, but some features (like forceAuthn) require changes I've done in the Tuakiri work.

I'll push in the README.md shortly.

**Comment by vladimir-mencl-eresearch** [comment]
Hi Bradley,

Sorry, took me a while to get to it - happy with this README.md?

Cheers,
Vlad

**Pull request merged**
